#!/bin/sh
# Copyright (C) 2026 Ayan Das
# SPDX-License-Identifier: GPL-3.0-or-later

# Inspects the backup and data-extraction policy an APK packages, with the build
# tools this module pins. Every check that fails is reported and the script exits 1.
#
# Usage: tools/verify-private-storage.sh APK...
#
# Requires ANDROID_HOME (or ANDROID_SDK_ROOT). Every APK must refuse backup in
# its packaged manifest, point both rule attributes at the compiled rule
# resources, exclude every sensitive domain in the legacy, cloud-backup and
# device-transfer modes, opt into no further mode, declare no storage or backup
# permission, and leave no census entry eligible in any mode.
#
# The census is rule-driven: the paths are the ones the production path policy
# names, generated by PrivateCensusTest into tools/fixtures/private-census.txt and
# placed here as nonempty synthetic files, evaluated against the rules the APK
# itself packages. Nothing here is a backup transport, account or device-transfer
# observation, and none of it says what a particular OEM implementation does.
#
# Verdicts distinguish what the rules exclude from what the platform excludes on
# its own: the private root, the cache and the code cache leave the app's directory
# under no mode whatever the rules say, so at least one census entry must be
# excluded by rule for the packaged rules to have been checked at all.
# https://developer.android.com/identity/data/autobackup
#
# Sourcing this file with VERIFY_PRIVATE_STORAGE_LIB=1 defines the checks without
# running them; such a caller owns `failures` and must set `work` to a directory
# it owns. tools/verify-private-storage-tests.sh drives them that way.

set -eu

MODULE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
CATALOG="$MODULE/gradle/libs.versions.toml"
POLICY_SOURCE="$MODULE/app/src/main/kotlin/io/github/b_vitamins/slipbox/security/PrivateStoragePolicy.kt"
CENSUS_FIXTURE="$MODULE/tools/fixtures/private-census.txt"

# The directory every private store lives beneath, relative to the app's own
# directory. It is the platform's no-backup directory, which the platform
# excludes on its own as well as through the rules checked here.
PRIVATE_ROOT=no_backup

# The directories the platform keeps out of every mode by itself, within the two
# domains that carry the app's own directory.
INTRINSIC_ROOTS="$PRIVATE_ROOT cache code_cache"
INTRINSIC_DOMAINS="root device_root"

# Every domain a credential, an index, a checkout or a note can reach. `root` and
# `device_root` carry the private root itself; the rest are the domains Auto
# Backup would otherwise collect.
SENSITIVE_DOMAINS="root file database sharedpref external
device_root device_file device_database device_sharedpref"

# The rule modes the platform applies. The legacy file answers below the modern
# floor and the modern file at and above it; both must exclude everything.
LEGACY_MODE=legacy
MODERN_MODES="cloud-backup device-transfer"
MODERN_FLOOR=31

# Sections the data-extraction contract defines that this app does not opt into.
# `cross-platform-transfer` arrived for API 36.1 and would carry data to another
# operating system; naming it here refuses it rather than reading its rules as the
# previous section's.
UNAUTHORIZED_SECTIONS="cross-platform-transfer"

# The attributes a rule of this policy carries. Anything else, including one the
# platform defines for a wider transfer, is refused.
RULE_ATTRIBUTES="domain path"

# Application attributes that would widen what leaves the device or outlives an
# uninstall. Absent or false is the only acceptable state.
REFUSED_FLAGS="backupAgent fullBackupOnly restoreAnyVersion
requestLegacyExternalStorage preserveLegacyExternalStorage hasFragileUserData"

# Permissions that would move private data onto shared storage or hand it to a
# backup tool. A packaged manifest naming any of these fails.
REFUSED_PERMISSIONS="android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.MANAGE_EXTERNAL_STORAGE
android.permission.ACCESS_MEDIA_LOCATION
android.permission.READ_MEDIA_IMAGES
android.permission.READ_MEDIA_VIDEO
android.permission.READ_MEDIA_AUDIO
android.permission.READ_MEDIA_VISUAL_USER_SELECTED
android.permission.BACKUP"

# Each rule attribute, the resource it must name and the root element that
# resource must have.
RULE_RESOURCES="fullBackupContent:xml/backup_rules:full-backup-content
dataExtractionRules:xml/data_extraction_rules:data-extraction-rules"

failures=0

fail() {
    failures=$((failures + 1))
    echo "FAIL $*"
}

abort() {
    echo "FAIL $*" >&2
    exit 1
}

pin() {
    pinned=$(sed -n "s/^$1 = \"\\([^\"]*\\)\"\$/\\1/p" "$CATALOG")
    [ -n "$pinned" ] || abort "$CATALOG declares no $1"
    echo "$pinned"
}

digest() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

digest_of_input() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | cut -d' ' -f1
    else
        shasum -a 256 | cut -d' ' -f1
    fi
}

# Whether $1 is one of the words $2.
member() {
    for listed in $2; do
        [ "$listed" != "$1" ] || return 0
    done
    return 1
}

# The stores the production path policy declares, as "directory:per-credential"
# words, read from the enum rather than from a second list kept here.
declared_stores() {
    sed -n 's/^    [A-Za-z]*("\([a-z]*\)", \([a-z]*\)),$/\1:\2/p' "$POLICY_SOURCE"
}

dump_xmltree() {
    "$aapt2" dump xmltree --file "$2" "$1"
}

# Attributes of the first $1 element in the tree $2, as "name=value" lines with
# the android name space, the attribute identifier and the raw echo removed.
element_attributes() {
    awk -v want="$1" '
        /^[[:space:]]*E: / {
            inside = ($2 == want)
            next
        }
        inside && /^[[:space:]]*A: / {
            line = $0
            sub(/^[[:space:]]*A: /, "", line)
            sub(/^http:\/\/schemas\.android\.com\/apk\/res\/android:/, "", line)
            sub(/\(0x[0-9a-f]+\)/, "", line)
            sub(/ \(Raw: .*$/, "", line)
            gsub(/"/, "", line)
            print line
        }
    ' "$2"
}

value_of() {
    sed -n "s/^$2=//p" "$1" | head -1
}

# Every permission the tree $1 declares.
declared_permissions() {
    awk '
        /^[[:space:]]*E: / {
            inside = ($2 == "uses-permission" || $2 == "uses-permission-sdk-23")
            next
        }
        inside && match($0, /name="[^"]*"/) {
            print substr($0, RSTART + 6, RLENGTH - 7)
        }
    ' "$1"
}

root_element_of() {
    awk '/^[[:space:]]*E: / { print $2; exit }' "$1"
}

# Attributes in the tree $1 that this policy does not declare, as "element|name"
# words: a rule carries $RULE_ATTRIBUTES and a section or root element carries
# none. A widening attribute is refused here rather than ignored by the listing,
# which reads only the two it knows.
unexpected_attributes() {
    awk -v allowed=" $RULE_ATTRIBUTES " '
        /^[[:space:]]*E: / {
            element = $2
            next
        }
        element != "" && /^[[:space:]]*A: / {
            name = $0
            sub(/^[[:space:]]*A: /, "", name)
            sub(/^http:\/\/schemas\.android\.com\/apk\/res\/android:/, "", name)
            sub(/[=(].*$/, "", name)
            if (element == "exclude" || element == "include") {
                if (!index(allowed, " " name " ")) {
                    print element "|" name
                }
            } else {
                print element "|" name
            }
        }
    ' "$1"
}

# The rules in the tree $1 as "mode|kind|domain|path" words. A rule outside any
# section keeps an empty mode, and a section outside the modes this app opts into
# is named as itself with a "section" rule of its own, so `inspect_rules` refuses
# either rather than reading it as the mode before it.
rule_listing() {
    awk -v legacy="$LEGACY_MODE" -v modes=" $MODERN_MODES " '
        function flush() {
            if (kind != "") {
                print mode "|" kind "|" domain "|" path
            }
            kind = ""
            domain = ""
            path = ""
        }
        /^[[:space:]]*E: / {
            flush()
            if ($2 == "full-backup-content") {
                mode = legacy
            } else if ($2 == "data-extraction-rules") {
                mode = ""
            } else if (index(modes, " " $2 " ")) {
                mode = $2
            } else if ($2 == "exclude" || $2 == "include") {
                kind = $2
            } else {
                mode = $2
                print mode "|section||"
            }
            next
        }
        /^[[:space:]]*A: / {
            if (kind == "") {
                next
            }
            if (match($0, /domain="[^"]*"/)) {
                domain = substr($0, RSTART + 8, RLENGTH - 9)
            } else if (match($0, /path="[^"]*"/)) {
                path = substr($0, RSTART + 6, RLENGTH - 7)
            }
        }
        END { flush() }
    ' "$1"
}

# Whether the entry $3 of domain $2 is `intrinsic`, `excluded` or `eligible` under
# the rules $4 in mode $1, as the platform reads them: the no-backup, cache and
# code-cache directories of the app's own domains never leave it whatever the rules
# say, an exclusion covers a whole domain at `.` and a directory prefix otherwise,
# an exclusion outranks an inclusion, and one inclusion in a mode leaves whatever it
# omits excluded.
# https://developer.android.com/identity/data/autobackup
verdict_for() {
    awk -F'|' -v mode="$1" -v domain="$2" -v entry="$3" \
        -v intrinsic_roots="$INTRINSIC_ROOTS" -v intrinsic_domains=" $INTRINSIC_DOMAINS " '
        function covers(rule, path) {
            if (rule == "." || rule == "") {
                return 1
            }
            sub(/\/+$/, "", rule)
            return (path == rule || index(path, rule "/") == 1)
        }
        function intrinsic(domain, path, roots, count, index_) {
            if (!index(intrinsic_domains, " " domain " ")) {
                return 0
            }
            count = split(intrinsic_roots, roots, " ")
            for (index_ = 1; index_ <= count; index_++) {
                if (covers(roots[index_], path)) {
                    return 1
                }
            }
            return 0
        }
        BEGIN {
            if (intrinsic(domain, entry)) {
                print "intrinsic"
                answered = 1
                exit
            }
        }
        $1 != mode { next }
        $2 == "exclude" && $3 == domain && covers($4, entry) { excluded = 1 }
        $2 == "include" {
            included++
            if ($3 == domain && covers($4, entry)) {
                covered = 1
            }
        }
        END {
            if (!answered) {
                print (excluded || (included && !covered)) ? "excluded" : "eligible"
            }
        }
    ' "$4"
}

control() {
    controls=$((controls + 1))
    verdict=$(verdict_for "$1" "$2" "$3" "$fixture")
    [ "$verdict" = "$4" ] ||
        fail "the evaluator calls $2:$3 in $1 $verdict rather than $4 ($5)"
}

# Checks that the evaluator can answer all three ways and discriminates on mode,
# domain, path boundary and the platform's own exclusions. Without these controls an
# evaluator that only ever said `excluded` would pass every census below.
inspect_evaluator() {
    controls=0
    fixture="$work/control-rules"
    cat >"$fixture" <<EOF
$LEGACY_MODE|exclude|file|vault
cloud-backup|exclude|file|vault
cloud-backup|include|file|public
cloud-backup|include|root|$PRIVATE_ROOT
EOF
    control "$LEGACY_MODE" file vault/credential.bin excluded "an excluded subtree"
    control "$LEGACY_MODE" file vault excluded "the excluded directory itself"
    control "$LEGACY_MODE" file vaultish/notes.org eligible "a name the exclusion only prefixes"
    control "$LEGACY_MODE" database vault/credential.bin eligible "another domain"
    control device-transfer file vault/credential.bin eligible "a mode with no rule of its own"
    control cloud-backup file public/readme.txt eligible "an included path"
    control cloud-backup file checkout/notes.org excluded "a path an inclusion omits"

    # What the platform excludes by itself, which no rule reaches either way.
    control "$LEGACY_MODE" root "$PRIVATE_ROOT/vault/00/credential.bin" intrinsic \
        "the private root with no rule at all"
    control cloud-backup root "$PRIVATE_ROOT/vault/00/credential.bin" intrinsic \
        "the private root an inclusion names"
    control device-transfer device_root cache/scratch.bin intrinsic "a cache in the protected root"
    control "$LEGACY_MODE" root code_cache/compiled.dex intrinsic "the code cache"
    control "$LEGACY_MODE" file cache/scratch.bin eligible "a cache name in another domain"
    control "$LEGACY_MODE" root files/sources.json eligible "a root path only a rule excludes"
    echo "EVALUATOR $controls control verdicts as specified, each answer among them"
}

# Places one nonempty synthetic file under $1 per committed census entry and
# prints the census it placed. The private paths are the production policy's own,
# generated into the fixture by PrivateCensusTest rather than spelled again here;
# a line this script cannot account for ends the run. Nothing written is a
# credential: each file holds the same marked filler.
build_payload() {
    payload_root=$1
    placed=0
    read_lines=0
    while IFS='|' read -r domain path origin what; do
        read_lines=$((read_lines + 1))
        case ${domain:-#} in
        '#'*) continue ;;
        esac
        [ -n "$path" ] && [ -n "$origin" ] && [ -n "$what" ] ||
            abort "$CENSUS_FIXTURE line $read_lines is not domain|path|origin|what"
        member "$domain" "$SENSITIVE_DOMAINS" ||
            abort "$CENSUS_FIXTURE line $read_lines names the unknown domain $domain"
        member "$origin" "policy platform" ||
            abort "$CENSUS_FIXTURE line $read_lines names the unknown origin $origin"
        case $path in
        /* | *..* | */)
            abort "$CENSUS_FIXTURE line $read_lines names $path, not a relative private path"
            ;;
        esac
        place "$domain" "$path" "$origin" "$what"
        placed=$((placed + 1))
    done <"$CENSUS_FIXTURE"
    [ "$placed" -gt 0 ] || abort "$CENSUS_FIXTURE holds no census entry"
}

place() {
    file="$payload_root/$1/$2"
    mkdir -p "$(dirname -- "$file")"
    printf 'synthetic-payload %s\n' "$4" >"$file"
    echo "$1|$2|$3|$4"
}

# Checks the rules $1 of $2 for the exclusions every mode must carry, and for a
# mode this app does not opt into.
inspect_rules() {
    listing=$1
    label=$2

    sectionless=$(grep -c '^|' "$listing" || true)
    [ "$sectionless" -eq 0 ] ||
        fail "$label carries $sectionless rules outside any backup mode"

    for mode in $(cut -d'|' -f1 "$listing" | sort -u); do
        if member "$mode" "$LEGACY_MODE $MODERN_MODES"; then
            continue
        elif member "$mode" "$UNAUTHORIZED_SECTIONS"; then
            fail "$label opts into the $mode section, which this app does not authorize"
        else
            fail "$label packages the unrecognized rule section <$mode>"
        fi
    done

    for rule in $(awk -F'|' '$2 == "include" { print $1 "|" $3 "|" $4 }' "$listing"); do
        included=${rule#*|}
        fail "$label includes ${included%|*}:${included##*|} in ${rule%%|*}," \
            "narrowing that mode to a whitelist"
    done

    for mode in $LEGACY_MODE $MODERN_MODES; do
        rules=$(awk -F'|' -v mode="$mode" '$1 == mode' "$listing" | wc -l | tr -d ' ')
        [ "$rules" -gt 0 ] || fail "$label declares no $mode rule at all"
        for domain in $SENSITIVE_DOMAINS; do
            grep -qx "$mode|exclude|$domain|\\." "$listing" ||
                fail "$label does not exclude the whole $domain domain in $mode"
        done
        echo "  $mode carries $rules rules"
    done
}

# Checks every census entry against the rules $1 of $2, in every mode, and that
# the rules themselves account for at least one of them.
inspect_census() {
    listing=$1
    label=$2
    counted=0
    ruled=0
    platform_held=0
    while IFS='|' read -r domain path origin what; do
        counted=$((counted + 1))
        [ -s "$payload_root/$domain/$path" ] ||
            fail "$label was to evaluate $domain:$path ($what), which no payload file holds"
        for mode in $LEGACY_MODE $MODERN_MODES; do
            verdict=$(verdict_for "$mode" "$domain" "$path" "$listing")
            case $verdict in
            excluded) [ "$mode" != "$LEGACY_MODE" ] || ruled=$((ruled + 1)) ;;
            intrinsic) [ "$mode" != "$LEGACY_MODE" ] || platform_held=$((platform_held + 1)) ;;
            eligible) fail "$label leaves $domain:$path ($origin, $what) eligible in $mode" ;;
            *) fail "$label produced no verdict for $domain:$path in $mode" ;;
            esac
        done
    done <"$census"
    [ "$counted" -gt 0 ] || fail "$label was given an empty census"
    [ "$ruled" -gt 0 ] ||
        fail "$label excludes no census entry by rule; the platform's own exclusions carry it all"
    echo "  census $counted entries, none eligible in any mode: $ruled excluded by rule and" \
        "$platform_held by the platform itself"
}

# Checks what the APK $1 packages, using the fresh directory $2.
inspect_apk() {
    apk=$1
    tree=$2
    echo "APK $apk sha256 $(digest "$apk")"

    mkdir "$tree" || abort "$tree is not a fresh inspection directory"
    if ! dump_xmltree "$apk" AndroidManifest.xml >"$tree/manifest" 2>"$tree/errors"; then
        abort "$apk packages no readable manifest: $(tr '\n' ' ' <"$tree/errors")"
    fi
    element_attributes manifest "$tree/manifest" >"$tree/root"
    element_attributes application "$tree/manifest" >"$tree/application"
    element_attributes uses-sdk "$tree/manifest" >"$tree/uses-sdk"

    backup=$(value_of "$tree/application" allowBackup)
    [ "$backup" = false ] || fail "$apk declares android:allowBackup=${backup:-absent}, not false"
    for flag in $REFUSED_FLAGS; do
        value=$(value_of "$tree/application" "$flag")
        case ${value:-absent} in
        absent | false) ;;
        *) fail "$apk declares android:$flag=$value" ;;
        esac
    done
    shared=$(value_of "$tree/root" sharedUserId)
    [ -z "$shared" ] ||
        fail "$apk shares its data directory through android:sharedUserId=$shared"

    for name in $(declared_permissions "$tree/manifest"); do
        for refused in $REFUSED_PERMISSIONS; do
            [ "$name" != "$refused" ] || fail "$apk declares $name"
        done
    done

    packaged_min=$(value_of "$tree/uses-sdk" minSdkVersion)
    packaged_target=$(value_of "$tree/uses-sdk" targetSdkVersion)
    [ "$packaged_min" = "$min_api" ] ||
        fail "$apk declares minSdkVersion ${packaged_min:-absent}, not the pinned $min_api"
    [ "$packaged_target" = "$target_api" ] ||
        fail "$apk declares targetSdkVersion ${packaged_target:-absent}, not the pinned $target_api"
    case ${packaged_min:-absent} in
    [0-9]*)
        [ "$packaged_min" -ge "$MODERN_FLOOR" ] ||
            echo "  minSdkVersion $packaged_min needs the legacy rules through API" \
                "$((MODERN_FLOOR - 1))"
        ;;
    esac

    if ! "$aapt2" dump resources "$apk" >"$tree/resources" 2>"$tree/errors"; then
        abort "$apk packages no readable resource table: $(tr '\n' ' ' <"$tree/errors")"
    fi

    : >"$tree/rules"
    for entry in $RULE_RESOURCES; do
        attribute=${entry%%:*}
        rest=${entry#*:}
        expected=${rest%%:*}
        expected_root=${rest#*:}

        reference=$(value_of "$tree/application" "$attribute")
        case ${reference:-absent} in
        @0x*) ;;
        *)
            fail "$apk names no compiled resource in android:$attribute (${reference:-absent})"
            continue
            ;;
        esac
        identifier=${reference#@}
        named=$(awk -v want="$identifier" '$1 == "resource" && $2 == want { print $3; exit }' \
            "$tree/resources")
        [ "$named" = "$expected" ] ||
            fail "$apk points android:$attribute at ${named:-no packaged resource}, not $expected"
        [ -n "$named" ] || continue

        file=$(awk -v want="$identifier" '
            $1 == "resource" && $2 == want { found = 1; next }
            found && $1 == "resource" { exit }
            found {
                for (field = 1; field <= NF; field++) {
                    if ($field ~ /^res\//) {
                        print $field
                        exit
                    }
                }
            }
        ' "$tree/resources")
        if [ -z "$file" ]; then
            fail "$apk packages no file for $named"
            continue
        fi

        tree_file="$tree/$(basename "$file")"
        if ! dump_xmltree "$apk" "$file" >"$tree_file" 2>"$tree/errors"; then
            fail "$apk packages $file unreadably: $(tr '\n' ' ' <"$tree/errors")"
            continue
        fi
        packaged_root=$(root_element_of "$tree_file")
        [ "$packaged_root" = "$expected_root" ] ||
            fail "$apk packages $file rooted at ${packaged_root:-nothing}, not $expected_root"
        for unexpected in $(unexpected_attributes "$tree_file"); do
            fail "$apk declares ${unexpected#*|} on <${unexpected%%|*}> in $file," \
                "which this policy does not"
        done
        rule_listing "$tree_file" >>"$tree/rules"
        echo "  android:$attribute is $named at $file"
    done

    inspect_rules "$tree/rules" "$apk"
    inspect_census "$tree/rules" "$apk"
    sort "$tree/rules" >"$tree/sorted-rules"
    digest "$tree/sorted-rules" >>"$policy_digests"
}

main() {
    while [ $# -gt 0 ]; do
        case $1 in
        --)
            shift
            break
            ;;
        -*) abort "unknown option $1" ;;
        *) break ;;
        esac
    done
    [ $# -gt 0 ] || {
        echo "usage: tools/verify-private-storage.sh APK..." >&2
        exit 2
    }

    work=$(mktemp -d)
    trap 'rm -rf "$work"' EXIT INT TERM
    policy_digests="$work/policy-digests"
    : >"$policy_digests"

    inspect_evaluator

    census="$work/census"
    build_payload "$work/payload" >"$census"
    entries=$(grep -c . "$census" || true)
    stores=$(declared_stores | wc -l | tr -d ' ')
    [ "$stores" -gt 0 ] || abort "$POLICY_SOURCE declares no private store"
    [ "$entries" -gt "$stores" ] || abort "the census is too small to mean anything"
    for pair in $(declared_stores); do
        grep -q "^root|$PRIVATE_ROOT/${pair%%:*}/" "$census" ||
            abort "the census names no entry of the ${pair%%:*} store the policy declares"
    done
    domains=0
    for domain in $SENSITIVE_DOMAINS; do
        grep -q "^$domain|" "$census" || abort "the census reaches no $domain entry"
        domains=$((domains + 1))
    done
    echo "CENSUS $entries entries over $stores declared stores and $domains domains, from" \
        "$(basename "$CENSUS_FIXTURE") sha256 $(digest "$CENSUS_FIXTURE"), placed as files:" \
        "rule-driven, not a device backup or transfer observation"

    apks=0
    for apk in "$@"; do
        [ -f "$apk" ] || abort "$apk does not exist"
        apks=$((apks + 1))
        inspect_apk "$apk" "$work/apk-$apks"
    done

    policies=$(sort -u "$policy_digests" | grep -c . || true)
    if [ "$policies" -eq 1 ]; then
        echo "POLICY all $apks APKs package the same rules, sha256 $(sort -u "$policy_digests")"
    else
        fail "the $apks APKs package $policies different rule sets"
    fi

    if [ "$failures" -eq 0 ]; then
        echo "PASS every packaged policy satisfies the checks above"
    else
        echo "FAILURES $failures"
        exit 1
    fi
}

sdk=${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}
[ -n "$sdk" ] || abort "ANDROID_HOME is not set"

build_tools_version=$(pin build-tools)
min_api=$(pin min-sdk)
target_api=$(pin target-sdk)

aapt2="$sdk/build-tools/$build_tools_version/aapt2"
[ -x "$aapt2" ] || abort "$aapt2 is not executable"
[ -f "$POLICY_SOURCE" ] || abort "$POLICY_SOURCE does not exist"
[ -s "$CENSUS_FIXTURE" ] || abort "$CENSUS_FIXTURE is missing or empty"

[ "${VERIFY_PRIVATE_STORAGE_LIB:-}" = 1 ] || main "$@"
